# Generated by Django 4.2.6 on 2023-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session",
            field=models.CharField(
                blank=True,
                max_length=350,
                null=True,
                unique=True,
                verbose_name="текущая сессия для оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                default="cash",
                max_length=10,
                verbose_name="способ оплаты",
            ),
        ),
    ]
