# Generated by Django 4.2.6 on 2023-10-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="название")),
                (
                    "preview",
                    models.ImageField(
                        null=True, upload_to="course/", verbose_name="превью"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание")),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="название")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "preview",
                    models.ImageField(
                        null=True, upload_to="course/", verbose_name="превью"
                    ),
                ),
                ("url", models.URLField(verbose_name="ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="курс",
                    ),
                ),
            ],
        ),
    ]
